version: "3"
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - sketchymine-net
    volumes:
      - db-volume:/var/lib/postgresql/data
  sketchymine-backend:
    image: registry.gitlab.com/saxion.nl/server-clients/dhi2v.so2/backend:latest
    ports:
      - "8443:3000"
    restart: always
    environment:
      DB_URL: ${DB_URL}
      SENTRY_DSN: ${SENTRY_DSN}
    depends_on:
      - db
    networks:
      - sketchymine-net

networks:
  sketchymine-net:

volumes:
  db-volume:
