version: "3"
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sm_db
  sketchymine-backend:
    image: registry.gitlab.com/saxion.nl/server-clients/dhi2v.so2/backend:latest
    ports:
      - "8443:3000"
    restart: always
    environment:
      DB_URL: ${DB_URL}
    depends_on:
      - db
