version: "3"
services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - sketchymine-net
    volumes:
      - db-volume:/var/lib/postgresql/data
  sketchymine-backend:
    image: registry.gitlab.com/saxion.nl/server-clients/dhi2v.so2/backend:latest
    container_name: sketchymine-backend
    ports:
      - "8443:3000"
    restart: always
    environment:
      DB_URL: ${DB_URL}
      SENTRY_DSN: ${SENTRY_DSN}
    depends_on:
      - db
    networks:
      - sketchymine-net
  pg_admin:
    image: dpage/pgadmin4
    container_name: sketchymine-db-pgadmin4
    restart: always
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sketchymine.philipposslicher.tech
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASS}
    depends_on:
      - db
    networks:
      - sketchymine-net
    volumes:
      - pga-volume:/servers.json

networks:
  sketchymine-net:

volumes:
  db-volume:
  pga-volume:
