version: "3"
services:
  db_local:
    image: 'postgres:latest'
    container_name: sketchymine-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  pg_admin:
    image: dpage/pgadmin4
    container_name: sketchymine-db-pgadmin4
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: noreply@sketchymine.philipposslicher.tech
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASS}
